import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });


/**
 @notice layout.js is our core file of our application
 * Here we are wrapping all our children(files and folders) inside our providers!!!
 @dev This file is the complete and common to all layout of our application!!!
 */


export const metadata = {
  title: "GeminiAI ChatBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className} style={{fontFamily:"monospace"}}>

        <Providers>
          {children}
        </Providers>
      </body>
    </html>
    </ClerkProvider>
  ); 
} 